owner: jjohnson
name: rmats
categories:
  - Transcriptomics
description: rMATS detects differential alternative splicing events from RNA-Seq
long_description: |
  rMATS is a computational tool to detect differential alternative splicing events from RNA-Seq data. 
  The statistical model of MATS calculates the P-value and false discovery rate that the difference 
  in the isoform ratio of a gene between two conditions exceeds a given user-defined threshold. 
  From the RNA-Seq data, MATS can automatically detect and analyze alternative splicing events 
  corresponding to all major types of alternative splicing patterns. 
  rMATS handles replicate RNA-Seq data from both paired and unpaired study design.

homepage_url:  https://github.com/Xinglab/rmats-turbo
remote_repository_url: https://github.com/jj-umn/galaxytools/tree/master/rmats
type: unrestricted
