categories:
- Variant Analysis
- Transcriptomics
description: DeFuse - gene fusion discovery from RNA-Seq data
long_description: |
  deFuse - gene fusion discovery using RNA-Seq data

  deFuse is a software package for gene fusion discovery using RNA-Seq data. 
  The software uses clusters of discordant paired end alignments 
  to inform a split read alignment analysis for finding fusion boundaries.  
  The software also employs a number of heuristic filters in an attempt 
  to reduce the number of false positives and produces 
  a fully annotated output for each predicted fusion.

  http://sourceforge.net/apps/mediawiki/defuse/

  https://bitbucket.org/dranew/defuse

name: defuse
owner: jjohnson
remote_repository_url: https://github.com/jj-umn/galaxytools/tree/master/defuse
type: unrestricted
